apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector: 
    component: web #samain dengan template -> metadata -> labels -> key:value yang ada di sini
  ports:
    - port: 3000
      targetPort: 3000
