apiVersion: networking.k8s.io/v1
kind: Ingress #Object agar bisa node nya bisa diakses dari luar (bukan dari sesama pods aja)
metadata:
  name: ingress-service
  labels:
    name: ingress-service
  annotations:
    kubernetes.io/ingress.class: 'nginx' #bikin ingress controller based nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    # ADD ANNOTATION
    nginx.ingress.kubernetes.io/rewrite-target: /$1  #Kalau misal ada /api, nanti /api nya akan diREWRITE jadi "/" aja
    # UPDATE ANNOTATION
spec:
  rules:
    - http:
        paths:
        - pathType: Prefix
          path: "/?(.*)"
          backend:
            service:
              name: client-cluster-ip-service #Diambil dari client-cluster-ip-service.yaml:metadata:name
              port: 
                number: 3000
        - pathType: Prefix
          path: "/api/?(.*)"
          backend:
            service:
              name: server-cluster-ip-service #Diambil dari server-cluster-ip-service.yaml:metadata:name
              port:
                number: 5000

